services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  node-app:
    build:
      context: .
    container_name: express-people-dictionary
    ports:
      - 3050:3050
    depends_on:
      - mongodb
    env_file: ./.env
    volumes:
      - .:/app

volumes:
  mongo-data: